# Generated by Django 6.0.2 on 2026-03-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='delete_after_days',
            field=models.IntegerField(choices=[(0, 'Не видаляти'), (30, '30 днів'), (60, '60 днів'), (90, '90 днів')], default=0, help_text='Кількість днів після останнього входу, коли акаунт буде видалено автоматично.', verbose_name='Автовидалення після бездії (днів)'),
        ),
    ]
