version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_HOST_USER=a2d271775fe4cc
      - EMAIL_HOST_PASSWORD=7f194aa1e5f324
      - EMAIL_PORT=2525
      - EMAIL_USE_TLS=True
      - DEFAULT_FROM_EMAIL=PawMatch <noreply@pawmatch.app>
    depends_on:
      - redis

  worker_default:
    build: .
    volumes:
      - .:/app
    command: celery -A qa_board worker -l info -Q default
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_HOST_USER=a2d271775fe4cc
      - EMAIL_HOST_PASSWORD=7f194aa1e5f324
      - EMAIL_PORT=2525
      - EMAIL_USE_TLS=True
      - DEFAULT_FROM_EMAIL=PawMatch <noreply@pawmatch.app>
    depends_on:
      - redis

  worker_email:
    build: .
    volumes:
      - .:/app
    command: celery -A qa_board worker -l info -Q email
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - EMAIL_HOST=sandbox.smtp.mailtrap.io
      - EMAIL_HOST_USER=a2d271775fe4cc
      - EMAIL_HOST_PASSWORD=7f194aa1e5f324
      - EMAIL_PORT=2525
      - EMAIL_USE_TLS=True
      - DEFAULT_FROM_EMAIL=PawMatch <noreply@pawmatch.app>
    depends_on:
      - redis
