# Generated by Django 4.2.30 on 2026-04-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('task_data', models.TextField()),
                ('result', models.TextField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
