# Generated by Django 4.2.30 on 2026-04-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_services', '0002_asynctaskresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynctaskresult',
            options={'ordering': ['-completed_at'], 'verbose_name': 'Результат асинхронної задачі', 'verbose_name_plural': 'Результати асинхронних задач'},
        ),
        migrations.AlterField(
            model_name='asynctaskresult',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Час завершення'),
        ),
        migrations.AlterField(
            model_name='asynctaskresult',
            name='result',
            field=models.TextField(verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='asynctaskresult',
            name='task_data',
            field=models.TextField(verbose_name='Дані задачі'),
        ),
        migrations.AlterField(
            model_name='asynctaskresult',
            name='task_name',
            field=models.CharField(max_length=255, verbose_name='Назва задачі'),
        ),
    ]
