# Generated by Django 6.0.2 on 2026-03-03 12:29

import django.db.models.deletion
import surveys.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст питання')),
                ('question_type', models.CharField(choices=[('choice', 'Вибір варіанту'), ('scale', 'Шкала 1-10')], default='choice', max_length=10, verbose_name='Тип питання')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Питання',
                'verbose_name_plural': 'Питання',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('icon', models.CharField(default='📋', max_length=10, verbose_name='Іконка')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст варіанту')),
                ('score', models.IntegerField(default=0, verbose_name='Числова оцінка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='surveys.question', verbose_name='Питання')),
            ],
            options={
                'verbose_name': 'Варіант відповіді',
                'verbose_name_plural': 'Варіанти відповідей',
                'ordering': ['score'],
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Назва')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('max_participants', models.PositiveIntegerField(default=5, verbose_name='Максимальна кількість учасників')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_surveys', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surveys', to='surveys.surveycategory', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Опитування',
                'verbose_name_plural': 'Опитування',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.survey', verbose_name='Опитування'),
        ),
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_code', models.CharField(default=surveys.models.generate_session_code, max_length=8, unique=True, verbose_name='Код сесії')),
                ('status', models.CharField(choices=[('pending', 'Очікування учасників'), ('active', 'Активна'), ('completed', 'Завершена')], default='pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Організатор')),
                ('participants', models.ManyToManyField(blank=True, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Учасники')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='surveys.survey', verbose_name='Опитування')),
            ],
            options={
                'verbose_name': 'Сесія опитування',
                'verbose_name_plural': 'Сесії опитувань',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompatibilityResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(verbose_name='Сумісність (%)')),
                ('strengths', models.JSONField(default=list, verbose_name='Спільні сильні сторони')),
                ('weaknesses', models.JSONField(default=list, verbose_name='Розбіжності')),
                ('lifestyle_tags', models.JSONField(default=list, verbose_name='Теги стилю життя')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_user1', to=settings.AUTH_USER_MODEL, verbose_name='Учасник 1')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_as_user2', to=settings.AUTH_USER_MODEL, verbose_name='Учасник 2')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='surveys.surveysession', verbose_name='Сесія')),
            ],
            options={
                'verbose_name': 'Результат сумісності',
                'verbose_name_plural': 'Результати сумісності',
                'unique_together': {('session', 'user1', 'user2')},
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scale_value', models.IntegerField(blank=True, null=True, verbose_name='Числова оцінка (1-10)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='surveys.question', verbose_name='Питання')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='surveys.answeroption', verbose_name='Обраний варіант')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='surveys.surveysession', verbose_name='Сесія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Відповідь користувача',
                'verbose_name_plural': 'Відповіді користувачів',
                'unique_together': {('session', 'user', 'question')},
            },
        ),
    ]
